/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployeePayrollMph;

import java.awt.*;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.imageio.ImageIO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Cal
 */
public class Employee extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        conn = myMotorPHdb.java_myMotorPhdb();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation (size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_sss = new javax.swing.JTextField();
        txt_philhealth = new javax.swing.JTextField();
        txt_tin = new javax.swing.JTextField();
        txt_pagibig = new javax.swing.JTextField();
        txt_basicsalSM = new javax.swing.JTextField();
        txt_hourlyRate = new javax.swing.JTextField();
        txt_phoneallowance = new javax.swing.JTextField();
        txt_clothingAllowance = new javax.swing.JTextField();
        txt_rsa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        txt_position = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_immspr = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_datehired = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();

        jLabel25.setText("jLabel25");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel1.setText("Employee Details");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_search.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        txt_search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel2.setText("Search Employee:");

        jLabel3.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel3.setText("Employee ID:");

        jLabel4.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel4.setText("Surname:");

        jLabel5.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel6.setText("Date of Birth:");

        r_male.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        r_male.setText("Male");
        r_male.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        r_female.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        r_female.setText("Female");
        r_female.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel7.setText("Gender:");

        jLabel8.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel8.setText("E-add:");

        jLabel9.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel9.setText("Address:");

        jLabel10.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel10.setText("Contact No:");

        txt_id.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_surname.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_firstname.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_dob.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_email.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_contact.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_address.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel11.setText("Department:");

        jLabel12.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel12.setText("SSS No:");

        jLabel13.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel13.setText("Philhealth No:");

        jLabel14.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel14.setText("TIN No:");

        jLabel15.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel15.setText("Pag-ibig No:");

        jLabel16.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel16.setText("Basic Salary SM:");

        jLabel17.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel17.setText("Hourly Rate:");

        jLabel18.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel18.setText("Phone Alw:");

        txt_sss.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_philhealth.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_tin.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_pagibig.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_basicsalSM.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_hourlyRate.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_phoneallowance.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_clothingAllowance.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_rsa.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel19.setText("Clothing Alw:");

        jLabel20.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel20.setText("Status:");

        jLabel21.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel21.setText("Position:");

        txt_status.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_position.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel22.setText("Imm. Supr:");

        txt_immspr.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel23.setText("RSA:");

        jLabel24.setFont(new java.awt.Font("a_Broker", 1, 12)); // NOI18N
        jLabel24.setText("Date Hired:");

        txt_datehired.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_department.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cal\\Desktop\\icon\\attach.png")); // NOI18N
        jButton1.setText("Attach");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cal\\Desktop\\icon\\update icon.png")); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cal\\Desktop\\icon\\erase-128.png")); // NOI18N
        jButton4.setText("Clear");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("a_Broker", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cal\\Desktop\\icon\\delete_16x16.gif")); // NOI18N
        jButton5.setText("Delete");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r_male, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(r_female)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txt_surname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                    .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_firstname))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_immspr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                    .addComponent(txt_position, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_status, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_contact, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_dob))
                                                .addGap(40, 40, 40)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_datehired, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txt_hourlyRate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_basicsalSM, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_pagibig, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tin, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_philhealth, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_sss, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_rsa, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_department)
                                            .addComponent(txt_phoneallowance)
                                            .addComponent(txt_clothingAllowance))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(78, 78, 78))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_search, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(30, 30, 30))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_sss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txt_philhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txt_tin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(r_male)
                            .addComponent(r_female)
                            .addComponent(jLabel15)
                            .addComponent(txt_pagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_basicsalSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel9)))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(txt_immspr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(txt_rsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel24)
                                            .addComponent(txt_datehired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txt_phoneallowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_clothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        gender = "Female";
        r_female.setSelected(true);
        r_male.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to add record?", "Add Record", JOptionPane.YES_NO_OPTION);
        if (x==0){
            
        }
        
        try{
            
            String sql = "insert into Employee_info"+"(Surname, First_Name, Gender, DoB, "
                    + "Email,Telephone, Address, Status, Position, Imm_Spr, sss, Philhealth,"
                    + " Tin, Pag_ibig, BasicSal, Hourly_Rate, Phone_Alw, Clothing_Alw, Rice_Sub, Designition"
                    + " , Date_Hired, Desination, Department, Image) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            
            pst = conn.prepareStatement(sql);
            
            pst.setString(1,txt_surname.getText());
            pst.setString(2, txt_firstname.getText());
            pst.setString(3, gender);
            pst.setString(4, txt_dob.getText());
            pst.setString(5, txt_email.getText());
            pst.setString(6, txt_contact.getText());
            pst.setString(7, txt_address.getText());
            pst.setString(8,  txt_status.getText());
            pst.setString(9, txt_position.getText());
            pst.setString(10, txt_immspr.getText());
            pst.setString(11, txt_sss.getText());
            pst.setString(12, txt_philhealth.getText());
            pst.setString(13, txt_tin.getText());
            pst.setString(14, txt_pagibig.getText());
            pst.setString(15, txt_basicsalSM.getText());
            pst.setString(16, txt_hourlyRate.getText());
            pst.setString(17,txt_phoneallowance.getText());
            pst.setString(18, txt_clothingAllowance.getText());
            pst.setString(19, txt_rsa.getText());
            pst.setString(20, txt_datehired.getText());
            pst.setString(21, txt_department.getText());
            pst.setBytes(22, person_image);
            
            
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"New data is saved successfully!");
            
}
catch (Exception e)
{
   
            JOptionPane.showMessageDialog(null,e);
            
}finally{
            
            try{
                rs.close();
                pst.close();
}
            catch (Exception e){

            }
}

try{        
        String sq = "select * from Employee_info where (id) NOT IN (select emp_id from Users)"; 
                
                pst = conn.prepareStatement(sq);
                rs = pst.executeQuery();
                
                while (rs.next());
                     String add1 = rs.getString("ID");
                     String add2 = rs.getString("First_Name");
                     String add3 = rs.getString("DoB");
                     String result = add3.replace("/","");
                     String add4 = rs.getString("Department");
                     
                String sql = "insert into Users ( username, password, division, emp_id) "
                        + "values ('"+add4+"', '"+add2+"', '"+result+"', '"+add1+"')";
                
                pst = conn.prepareStatement(sql);
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "The user account has been create succesfully: " +"Username: "+add2+" Password:" + result);
                
}catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
        
finally{
            
            try{
                rs.close();
                pst.close();
}
            catch (Exception e){
            
            }
            
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser  chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        
        try{
            
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024]; 
            
            for (int number;(number = fix.read(buf)) != -1;){
                bos.write(buf,0,number);
            }
            person_image = bos.toByteArray();
            
}catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
        }
        
            try{
                rs.close();
                pst.close();;
                
            }catch (Exception e){
            }

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        try{
            
            String sql = "select*from Employee_info where id = ?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs = pst.executeQuery();
            
                String add1 = rs.getString("ID");
                txt_id.setText(add1);
                
                String add2 = rs.getString("Surname");
                txt_surname.setText(add2);
                
                String add3 = rs.getString("First_Name");
                txt_firstname.setText(add3);
                
                String add4 = rs.getString("Gender");
                txt_dob.setText(add4);
                
                String add6 = rs.getString("DoB");
                txt_dob.setText(add6);
                
                String add5 = rs.getString("Email");
                txt_email.setText(add5);
                
                
                String add7 = rs.getString("Telephone");
                txt_contact.setText(add7);
                
                String add8 = rs.getString("Address");
                txt_address.setText(add8);
                
                String add9 = rs.getString("Status");
                txt_status.setText(add9);
                
                String add10 = rs.getString("Position");
                txt_position.setText(add10);
                
                String add11 = rs.getString("Imm_Spr");
                txt_immspr.setText(add11);
                
                String add12 = rs.getString("sss");
                txt_sss.setText(add12);
                
                String add13 = rs.getString("Philhealth");
               txt_philhealth.setText(add13);
                
                String add14 = rs.getString("Tin");
                txt_tin.setText(add14);
                
                String add15 = rs.getString("Pag_ibig");
                txt_pagibig.setText(add15);
                
                String add16 = rs.getString("BasicSal");
                txt_basicsalSM.setText(add16);
                
                String add17 = rs.getString("Hourly_Rate");
                txt_hourlyRate.setText(add17);
                
                String add18 = rs.getString("Phone_Alw");
                txt_phoneallowance.setText(add18);
                
                String add19 = rs.getString("Clothing_Alw");
                txt_clothingAllowance.setText(add19);
                
                String add20 = rs.getString("Rice_Sub");
                txt_rsa.setText(add20);
                
                String add21 = rs.getString("Date_Hired");
                txt_datehired.setText(add21);
                
                String add22 = rs.getString("Department");
                txt_department.setText(add22);
                
                String add23 = rs.getString("Gender");
                if(add23.equals("Male")){
                    r_male.setSelected(true);
}else{
                    r_female.setSelected(true);
                    
                }
                
            
                
            byte[] image = rs.getBytes("Image");
            ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(), Image.SCALE_DEFAULT));
            img.setIcon(imageIcon);
            
}catch (Exception e){
    
}finally{
            
            try{
                rs.close();;
                pst.close();;
}
catch (Exception e){
            }
        }
        
        
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        
        txt_id.setText("");
        txt_surname.setText("");
        txt_firstname.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_contact.setText("");
        txt_address.setText("");
        txt_status.setText("");
        txt_position.setText("");
        txt_immspr.setText("");
        txt_sss.setText("");
        txt_philhealth.setText("");
        txt_tin.setText("");
        txt_pagibig.setText("");
        txt_basicsalSM.setText("");
        txt_hourlyRate.setText("");
        txt_phoneallowance.setText("");
        txt_clothingAllowance.setText("");
        txt_rsa.setText("");
        txt_datehired.setText("");
        txt_department.setText("");
        txt_search.setText("");
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete record?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if (x==0){
        
        
        try{
            
            String sql = "delete from Employee_info where id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Record Deleted!");
            
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
                finally{
            
            try{
                rs.close();
                pst.close();
}
catch (Exception e){
    
}
            }
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         String val1 = txt_id.getText();
        int x = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to update record?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (x==0){
        
        
        try{
            
            String val2 = txt_surname.getText();
            String val3 = txt_firstname.getText();
            String val4 = txt_dob.getText();
            String val5 = txt_email.getText();
            String val6 = txt_contact.getText();
            String val7 = txt_address.getText();
            String val8 = txt_status.getText();
            String val9 = txt_position.getText();
            String val10 = txt_immspr.getText();
            String val11 =txt_sss.getText();
            String val12 = txt_philhealth.getText();
            String val13 = txt_tin.getText();
            String val14 = txt_pagibig.getText();
            String val15 = txt_basicsalSM.getText();
            String val16 = txt_hourlyRate.getText();
            String val17 = txt_phoneallowance.getText();
            String val18 = txt_clothingAllowance.getText();
            String val19 = txt_rsa.getText();
            String val20 = txt_datehired.getText();
            String val21 = txt_department.getText();
           
       
            
            
            
            
            
            
            
            
   String sql = "update Employee_info set ID = '"+val1+"', Surname = '"+val2+"', First_Name  = '"+val3+"', "
           + "DoB = '"+val4+"', Email = '"+val5+"', Telephone = '"+val6+"', Address = '"+val7+"', Status = '"+val8+"',"
           + "Position = '"+val9+"', Imm_Spr = '"+val10+"', sss = '"+val11+"', Philhealth = '"+val12+"', "
           + "Tin = '"+val13+"', Pag_ibig = '"+val14+"', BasicSal = '"+val15+"', Hourly_Rate = '"+val16+"',"
           + "Phone_Alw = '"+val17+"', Clothing_Alw = '"+val18+"', Rice_Sub = '"+val19+"',Date_Hired = '"+val20+"', "
           + "Department = '"+val21+"', Gender = '"+gender+"' where ID = '"+val1+"'  ";        
   
   pst = conn.prepareStatement(sql);
   pst.execute();
     JOptionPane.showInputDialog(null, "Record has been updated!");
            
            
}catch (Exception e){
    JOptionPane.showInputDialog(null, e);
}
    
    try{
             File file = new File(filename);
             FileInputStream fis = new FileInputStream(file);
             byte[] image = new byte[(int) file.length()];
             fis.read(image);
             
             String sql = "update Employee_info SET Image = ? where id = '"+val1+"'";
             pst = conn.prepareStatement(sql);
             pst.setBytes(1, image);
             pst.executeUpdate();
             pst.close();
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

    
} 
        finally{
            
            try{
                rs.close();
                pst.close();
}
            catch (Exception e){
            }
    }
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_basicsalSM;
    private javax.swing.JTextField txt_clothingAllowance;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_datehired;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_hourlyRate;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_immspr;
    private javax.swing.JTextField txt_pagibig;
    private javax.swing.JTextField txt_philhealth;
    private javax.swing.JTextField txt_phoneallowance;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_rsa;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_sss;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tin;
    // End of variables declaration//GEN-END:variables

private ImageIcon format =null;
String filename = null;
byte[] person_image = null;
    
    private String gender;

}


