/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployeePayrollMph;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
/**
 *
 * @author Cal
 */
public class SalaryUpdate extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
            
    /**
     * Creates new form SalaryUpdate
     */
    public SalaryUpdate() {
        initComponents();
        conn = myMotorPHdb.java_myMotorPhdb();
        
        
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation (size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        txt_Surname = new javax.swing.JTextField();
        txt_FirstName = new javax.swing.JTextField();
        txt_ImmSpr = new javax.swing.JTextField();
        txt_Dept = new javax.swing.JTextField();
        txt_BasicSal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        text_opt2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r_percentage = new javax.swing.JRadioButton();
        r_amount = new javax.swing.JRadioButton();
        txt_opt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel1.setText("Employee ID:");

        txt_search.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        txt_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel2.setText("Employee ID:");

        jLabel3.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel3.setText("Surname:");

        jLabel4.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel4.setText("First Name:");

        txt_empID.setEditable(false);
        txt_empID.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_Surname.setEditable(false);
        txt_Surname.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_FirstName.setEditable(false);
        txt_FirstName.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N

        txt_ImmSpr.setEditable(false);
        txt_ImmSpr.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        txt_ImmSpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ImmSprActionPerformed(evt);
            }
        });

        txt_Dept.setEditable(false);
        txt_Dept.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        txt_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DeptActionPerformed(evt);
            }
        });

        txt_BasicSal.setEditable(false);
        txt_BasicSal.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        txt_BasicSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BasicSalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel5.setText("Department:");

        jLabel6.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel6.setText("Immediate Spr:");

        jLabel7.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel7.setText("Basic Salary:");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("a_Broker", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cal\\Desktop\\OOP-TA\\update icon.png")); // NOI18N
        jButton1.setText("Update");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel8.setText("Update Salary by:");

        text_opt2.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        text_opt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        text_opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_opt2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel9.setText("Percentage:");

        jLabel10.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        jLabel10.setText("Amount:");

        r_percentage.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        r_percentage.setText("%");
        r_percentage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });

        r_amount.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        r_amount.setText("Amount");
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });

        txt_opt1.setFont(new java.awt.Font("a_Broker", 0, 12)); // NOI18N
        txt_opt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(r_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_search)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(r_amount))
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(text_opt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_Dept, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(txt_ImmSpr)
                                            .addComponent(txt_BasicSal)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(txt_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(462, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txt_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txt_ImmSpr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_BasicSal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r_percentage)
                    .addComponent(r_amount)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(67, 67, 67))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(373, Short.MAX_VALUE)
                    .addComponent(txt_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        
        try{
            String sql = "select * from Employee_info where id = ?";
            
            pst = conn.prepareStatement (sql);
            pst.setString (1, txt_search.getText());
            rs = pst.executeQuery();
            
            
            String add1 = rs.getString ("ID");
            txt_empID.setText(add1);
            
            String add2 = rs.getString ("Surname");
            txt_Surname.setText(add2);
            
            String add3 = rs.getString ("First_Name");
            txt_FirstName.setText(add3);
            
            String add4= rs.getString ("Imm_Spr");
            txt_ImmSpr.setText(add4);
            
            String add5 = rs.getString ("Department");
            txt_Dept.setText(add5);
            
            String add6 = rs.getString ("BasicSal");
            txt_BasicSal.setText(add6);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            
            try{
                rs.close();
                pst.close();
            
            
}catch (Exception e){
        }
        
        
        
        }
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_ImmSprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ImmSprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ImmSprActionPerformed

    private void txt_BasicSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BasicSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BasicSalActionPerformed

    private void txt_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DeptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        
        int salary = Integer.parseInt(txt_BasicSal.getText());

     
            if(r_percentage.isSelected() == true){
        
        int getPercentage = Integer.parseInt(txt_opt1.getText());
        int calcPercentage = salary/100*getPercentage + salary;
        String P = String.valueOf(calcPercentage);
        txt_BasicSal.setText(P);
        
        }else if (r_amount.isSelected() == true){
       
       int getAmount = Integer.parseInt (text_opt2.getText());
       int calAmount = salary +getAmount;
       String A = String.valueOf(calAmount);
       txt_BasicSal.setText(A);
        }

        try{
            String value1 = txt_empID.getText();
            String value2 = txt_BasicSal.getText();
            
            String sql = "update Employee_info set id = '"+value1+"', BasicSal = '"+value2+"' where id = '"+value1+"' ";
                    
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated!");
            
}catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
}
finally{
            try{
                rs.close();
                pst.close();
            
}catch (Exception e){
            }
        }


        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:
        
        r_amount.setSelected(true);
        r_percentage.setSelected(false);
        txt_opt1.setEnabled(false);
        text_opt2.setEditable(true);
        text_opt2.setEnabled(true);
        txt_opt1.setText("");
        
        
        
        
        
        
        
    }//GEN-LAST:event_r_amountActionPerformed

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
        
        r_amount.setSelected(false);
        r_percentage.setSelected(true);
        txt_opt1.setEnabled(true);
        text_opt2.setEditable(false);
        txt_opt1.setEnabled(true);
        text_opt2.setText("");

        
        
        
        
        
        
    }//GEN-LAST:event_r_percentageActionPerformed

    private void text_opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_opt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_opt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JTextField text_opt2;
    private javax.swing.JTextField txt_BasicSal;
    private javax.swing.JTextField txt_Dept;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_ImmSpr;
    private javax.swing.JTextField txt_Surname;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_opt1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
